import { Router, Request, Response } from 'express';
import crypto from 'crypto';
export const agentRouter=Router();
type CommandType='ADB_STATUS'|'ADB_REFRESH'|'ADB_DEVICE_INFO'|'ADB_DEVICE_PROPERTIES'|'ADB_LIST_PACKAGES'|'ADB_STORAGE_SUMMARY'|'ADB_PROCESSES';
type AgentState={agentId:string;hostname?:string;lastSeen:number;status?:any;devices?:any[];refreshedAt?:string;heartbeatAt?:string};
type Command={id:string;type:CommandType;serial?:string;createdAt:number};
const agents=new Map<string,AgentState>();const commands=new Map<string,Command[]>();const commandResults=new Map<string,{result?:any;error?:string;receivedAt:number}>();
function authorized(req:Request){const expected=process.env.LOCAL_AGENT_TOKEN,supplied=req.header('X-Agent-Token');if(!expected||!supplied)return false;const a=Buffer.from(supplied),b=Buffer.from(expected);return a.length===b.length&&crypto.timingSafeEqual(a,b);}
agentRouter.use((req,res,next)=>{if(!authorized(req))return res.status(401).json({error:'Invalid local agent token'});next();});
agentRouter.post('/register',(req,res)=>{const agentId=String(req.body?.agentId||'default'),old=agents.get(agentId);agents.set(agentId,{agentId,hostname:req.body?.hostname,lastSeen:Date.now(),status:req.body?.status??old?.status,devices:req.body?.devices??old?.devices,refreshedAt:old?.refreshedAt,heartbeatAt:req.body?.heartbeatAt||new Date().toISOString()});return res.json({ok:true,agentId,serverTime:new Date().toISOString()});});
agentRouter.get('/status',(req,res)=>{const agentId=String(req.query.agentId||'default'),agent=agents.get(agentId);if(!agent)return res.json({connected:false,agentId});const connected=Date.now()-agent.lastSeen<Number(process.env.AGENT_OFFLINE_MS||15000);return res.json({connected,agentId,lastSeen:new Date(agent.lastSeen).toISOString(),heartbeatAt:agent.heartbeatAt,status:agent.status,devices:agent.devices||[],refreshedAt:agent.refreshedAt});});
agentRouter.post('/commands',(req,res)=>{const agentId=String(req.body?.agentId||'default'),agent=agents.get(agentId);if(!agent||Date.now()-agent.lastSeen>=Number(process.env.AGENT_OFFLINE_MS||15000))return res.status(409).json({error:'Local forensic agent is offline'});const allowed:CommandType[]=['ADB_STATUS','ADB_REFRESH','ADB_DEVICE_INFO','ADB_DEVICE_PROPERTIES','ADB_LIST_PACKAGES','ADB_STORAGE_SUMMARY','ADB_PROCESSES'];const type=String(req.body?.type||'ADB_REFRESH') as CommandType;if(!allowed.includes(type))return res.status(400).json({error:'Unsupported forensic operation'});const serial=req.body?.serial?String(req.body.serial):undefined;const command:Command={id:crypto.randomUUID(),type,serial,createdAt:Date.now()};const queue=commands.get(agentId)||[];queue.push(command);commands.set(agentId,queue);return res.status(202).json({queued:true,commandId:command.id,type});});
agentRouter.get('/commands',(req,res)=>{const agentId=String(req.query.agentId||'default'),agent=agents.get(agentId);if(agent)agent.lastSeen=Date.now();const queue=commands.get(agentId)||[];commands.set(agentId,[]);return res.json({commands:queue});});
agentRouter.post('/commands/:id/result',(req,res)=>{const agentId=String(req.body?.agentId||'default'),agent=agents.get(agentId);if(!agent)return res.status(404).json({error:'Agent not registered'});agent.lastSeen=Date.now();const result=req.body?.result;commandResults.set(req.params.id,{result,error:req.body?.error,receivedAt:Date.now()});if(result?.status)agent.status=result.status;if(Array.isArray(result?.devices))agent.devices=result.devices;if(result?.refreshedAt)agent.refreshedAt=result.refreshedAt;return res.json({ok:true});});
export function getDefaultAgentSnapshot(){const agent=Array.from(agents.values())[0];if(!agent)return{connected:false,devices:[]};return{connected:Date.now()-agent.lastSeen<Number(process.env.AGENT_OFFLINE_MS||15000),agentId:agent.agentId,lastSeen:new Date(agent.lastSeen).toISOString(),heartbeatAt:agent.heartbeatAt,status:agent.status,devices:agent.devices||[],refreshedAt:agent.refreshedAt};}
export function queueDefaultAgentCommand(type:CommandType,serial?:string){const agent=Array.from(agents.values())[0];if(!agent||Date.now()-agent.lastSeen>=Number(process.env.AGENT_OFFLINE_MS||15000))return null;const command:Command={id:crypto.randomUUID(),type,serial,createdAt:Date.now()};const queue=commands.get(agent.agentId)||[];queue.push(command);commands.set(agent.agentId,queue);return command.id;}
export async function waitForAgentCommand(commandId:string,timeoutMs=15000){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){const result=commandResults.get(commandId);if(result){commandResults.delete(commandId);if(result.error)throw new Error(result.error);return result.result;}await new Promise(r=>setTimeout(r,200));}throw new Error('Local forensic agent did not return the requested ADB result in time');}
