import { Router, Request, Response } from 'express';
import { AdbManager } from '../adb/AdbManager';
import { DemoDataGenerator } from '../demo/DemoDataGenerator';
import { SecurityEngine } from '@smart-forensic/security-engine';
import { AuditLogger } from '../audit/AuditLogger';
import { prisma } from '../db/client';
import { AppInfo, ContactInfo, ProcessInfo, SmsInfo } from '@smart-forensic/shared';
import { getDefaultAgentSnapshot, queueDefaultAgentCommand, waitForAgentCommand } from './agent.routes';
export const devicesRouter=Router();const adbManager=new AdbManager();const securityEngine=new SecurityEngine();const isLocalAgent=process.env.LOCAL_AGENT_MODE==='true';
async function remote(serial:string,type:any){if(!getDefaultAgentSnapshot().connected)throw new Error('Local forensic agent is offline. Start the agent on the investigator PC and try again.');const id=queueDefaultAgentCommand(type,serial);if(!id)throw new Error('Local forensic agent is offline. Start the agent on the investigator PC and try again.');return waitForAgentCommand(id);}
function minimalApps(packages:string[]):AppInfo[]{return packages.slice(0,200).map(packageName=>({packageName,appName:packageName.split('.').at(-1)||packageName,versionName:'Unknown',versionCode:0,apkPath:'',installSource:'Unknown',isSystemApp:packageName.startsWith('com.android.'),isSideloaded:false,isDebuggable:false,requestedPermissions:[],grantedPermissions:[],dangerousPermissions:[],risk:securityEngine.analyzeApplication({packageName,appName:packageName,versionName:'Unknown',versionCode:0,apkPath:'',installSource:'Unknown',isSystemApp:packageName.startsWith('com.android.'),isSideloaded:false,isDebuggable:false,requestedPermissions:[],grantedPermissions:[],dangerousPermissions:[]})} as AppInfo));}
function parseProcesses(raw:string):ProcessInfo[]{const lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return lines.slice(1).map(line=>{const p=line.split(/\s+/);const pid=Number(p.find(x=>/^\d+$/.test(x))||0);const user=p[0]||'Unknown';const processName=p.at(-1)||'Unknown';return {pid,user,processName,cpuPercent:0,memoryKb:0,formattedMemory:'Unknown',status:'Running',isSuspicious:false} as ProcessInfo;});}
devicesRouter.get('/',async(_req,res)=>{try{return res.json(await prisma.device.findMany({orderBy:{lastSeenAt:'desc'}}));}catch(err:any){return res.status(500).json({error:err.message});}});
devicesRouter.get('/:serial',async(req:Request,res:Response)=>{try{const {serial}=req.params;const isDemo=serial.startsWith('DEMO');const info=isDemo?DemoDataGenerator.getDemoDeviceInfo(serial):isLocalAgent?await adbManager.getDeviceInfo(serial):(await remote(serial,'ADB_DEVICE_INFO')).deviceInfo;await AuditLogger.log({investigator:'Lead Forensics Investigator',action:'DEVICE_INFO_COLLECTED',targetDeviceSerial:adbManager.maskSerial(serial),status:'SUCCESS',details:`Collected device specifications for ${info.model} (Android ${info.androidVersion})`,ipAddress:req.ip});return res.json(info);}catch(err:any){return res.status(503).json({error:err.message});}});
devicesRouter.get('/:serial/apps',async(req:Request,res:Response)=>{try{const {serial}=req.params;const isDemo=serial.startsWith('DEMO');let apps:AppInfo[]=[];if(isDemo)apps=DemoDataGenerator.getDemoApplications();else if(isLocalAgent){for(const item of (await adbManager.getInstalledPackages(serial)).slice(0,50)){const meta=await adbManager.getPackageMetadata(serial,item.packageName);const appName=item.packageName.split('.').at(-1)||item.packageName;const appData:any={packageName:item.packageName,appName,versionName:meta.versionName,versionCode:meta.versionCode,apkPath:item.apkPath,installSource:meta.installSource,isSystemApp:item.isSystem,isSideloaded:meta.isSideloaded,isDebuggable:meta.isDebuggable,requestedPermissions:meta.requestedPermissions,grantedPermissions:meta.grantedPermissions,dangerousPermissions:meta.requestedPermissions.filter(p=>p.includes('SMS')||p.includes('CONTACTS')||p.includes('ACCESSIBILITY'))};apps.push({...appData,risk:securityEngine.analyzeApplication(appData)});}}else apps=minimalApps((await remote(serial,'ADB_LIST_PACKAGES')).packages||[]);return res.json({apps,total:apps.length,suspicious:apps.filter(a=>['SUSPICIOUS','HIGH_RISK','CRITICAL'].includes(a.risk.riskLevel)).length});}catch(err:any){return res.status(503).json({error:err.message});}});
devicesRouter.get('/:serial/contacts',async(req:Request,res:Response)=>{try{const {serial}=req.params;const isDemo=serial.startsWith('DEMO');const contacts:ContactInfo[]=isDemo?DemoDataGenerator.getDemoContacts():[];await AuditLogger.log({investigator:'Lead Forensics Investigator',action:'CONTACT_COLLECTION',targetDeviceSerial:adbManager.maskSerial(serial),status:'SUCCESS',details:`Retrieved ${contacts.length} authorized contact records`,ipAddress:req.ip});return res.json({contacts,total:contacts.length,permissionGranted:isDemo||contacts.length>0});}catch(err:any){return res.status(500).json({error:err.message});}});
devicesRouter.get('/:serial/sms',async(req:Request,res:Response)=>{try{const {serial}=req.params;const isDemo=serial.startsWith('DEMO');const sms:SmsInfo[]=isDemo?DemoDataGenerator.getDemoSms():[];await AuditLogger.log({investigator:'Lead Forensics Investigator',action:'SMS_COLLECTION',targetDeviceSerial:adbManager.maskSerial(serial),status:'SUCCESS',details:`Retrieved ${sms.length} authorized SMS records`,ipAddress:req.ip});return res.json({sms,total:sms.length,suspiciousCount:sms.filter(s=>s.isSuspicious).length,permissionGranted:isDemo||sms.length>0});}catch(err:any){return res.status(500).json({error:err.message});}});
devicesRouter.get('/:serial/processes',async(req:Request,res:Response)=>{try{const {serial}=req.params;const isDemo=serial.startsWith('DEMO');let processes:ProcessInfo[]=[];if(isDemo)processes=DemoDataGenerator.getDemoProcesses();else if(isLocalAgent){const raw=await adbManager.getRunningProcesses(serial);processes=raw.map(p=>({...p,...securityEngine.analyzeProcess(p)}));}else{const raw=(await remote(serial,'ADB_PROCESSES')).processes||'';processes=parseProcesses(raw).map(p=>({...p,...securityEngine.analyzeProcess(p)}));}return res.json({processes,total:processes.length,suspiciousCount:processes.filter(p=>p.isSuspicious).length});}catch(err:any){return res.status(503).json({error:err.message});}});
devicesRouter.get('/:serial/security',async(req:Request,res:Response)=>{try{const {serial}=req.params;const isDemo=serial.startsWith('DEMO');const deviceInfo=isDemo?DemoDataGenerator.getDemoDeviceInfo(serial):isLocalAgent?await adbManager.getDeviceInfo(serial):(await remote(serial,'ADB_DEVICE_INFO')).deviceInfo;const integrity=securityEngine.evaluateDeviceIntegrity(deviceInfo);return res.json({deviceInfo,securityScore:integrity.securityScore,riskLevel:integrity.riskLevel,indicators:integrity.indicators,scoreBreakdown:integrity.scoreBreakdown});}catch(err:any){return res.status(503).json({error:err.message});}});
